Use cygwin

diff --git a/.github/workflows/build.yaml b/.github/workflows/build.yaml
--- a/.github/workflows/build.yaml
+++ b/.github/workflows/build.yaml
@@ -35,6 +35,22 @@ jobs:
           ref: viewer
           path: .build-variables
       
+      - name: Install cygwin
+        if: runner.os == 'Windows'
+        uses: secondlife/setup-cygwin@v1
+
+      - name: Determine shell
+        id: shell
+        shell: bash
+        env:
+          WINDOWS: ${{ runner.os == 'Windows' }}
+        run: |
+          if [[ $WINDOWS == 'true' ]]; then
+            echo "::set-output name=shell::C:\cygwin64\bin\bash.exe --login --norc -eo pipefail -o igncr '{0}'"
+          else
+            echo '::set-output name=shell::bash'
+          fi
+      
       - name: Install autobuild 
         run: pip3 install autobuild
 
@@ -46,8 +62,12 @@ jobs:
           key: ${{ matrix.os }}-${{ matrix.addrsize }}-${{ matrix.configuration }}-${{ hashFiles('autobuild.xml') }} 
 
       - name: Build
-        shell: bash
+        shell: ${{ steps.shell.outputs.shell }} 
+        env:
+          WORKSPACE: ${{ github.workspace }}
         run: |
+          cd "$WORKSPACE"
+
           autobuild --quiet source_environment > .env 
           source .env
 
